name: Kodi Addon-Check

on:
  pull_request:
    branches:
      - matrix

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install --user kodi-addon-checker gh-pr-commenter==1.0.0

    - name: Extract job variables
      shell: bash
      run: echo "##[set-output name=addon;]$(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq)"
      id: extract_vars

    - name: Addon-Check
      run: $HOME/.local/bin/kodi-addon-checker --branch=${{ github.event.pull_request.base.ref }} --PR ${{ steps.extract_vars.outputs.addon }} | tee addon-checker.log

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Check out this message!"
        check_for_duplicate_msg: false  # OPTIONAL
    #- name: Job success
    #  if: ${{ success() }}
    #  shell: bash
    #  env:
    #    GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #  run: $HOME/.local/bin/gh-pr-commenter.py ${{ github.repository }} ${{ github.event.number }} bot-success-template.md addon-checker.log

    #- name: Job failure
    #  if: ${{ failure() }}
    #  shell: bash
    #  env:
    #    GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #  run: $HOME/.local/bin/gh-pr-commenter.py ${{ github.repository }} ${{ github.event.number }} bot-failure-template.md addon-checker.log

