name: Kodi Addon-Check2

on:
  pull_request:
    branches:
      - matrix

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install --user kodi-addon-checker

    - name: Echo vars
      run: echo ${{ github.event.pull_request.base.ref }}


