name: Kodi Addon-Check2

on:
  pull_request:
    branches:
      - matrix

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install --user kodi-addon-checker

    - name: Extract repo target branch
      shell: bash
      run: echo "##[set-output name=addon;]$(echo $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq)))"
      id: extract_branch

    - name: Echo vars
      run: echo $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq) #echo ${{ steps.extract_branch.outputs.branch }} #${{ github.event.pull_request.base.ref }}


